---
- hosts: localhost  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  gather_facts: False  # don't gather facts against localhost
  vars:
    instance_name: 'NamIt'
    key_name: 'oregon'
    instance_type: 't2.micro' # keep it free
    image: 'ami-0d6621c01e8c2de2c' # free ami from Amazon us-east-1 region
    vpc_subnet_id: 'subnet-12180559'
    group_id: 'sg-05b887bdb1fdb57fe'
    zone: 'us-west-2a'
    region: 'us-west-2'
  tasks:
    - name: create an aws instance
      ec2:
         key_name: "{{ key_name }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         count: 1
         instance_tags:
            Name: "{{ instance_name }}"
            BuildStatus: 'Provisioning'
         monitoring: no
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         group_id: "{{ group_id }}"
         zone: "{{ zone }}"
         region: "{{ region }}"
         assign_public_ip: yes
      register: ec2_instance
      tasks:
         - debug: var=ansible_all_ipv4_addresses
 
